using System;
using System.Collections.Generic;

namespace DesignPatternsGOG.CreationalPatterns.Builder.Product
{
    /// <summary>
    /// This is a class which defines the parts of the complex object which are to be generated by the builder pattern.
    /// </summary>
    class Vehicle
    {
        public string Model { get; set; }
        public string Engine { get; set; }
        public string Transmission { get; set; }
        public string Body { get; set; }
        public List<string> Accessories { get; set; }

        public Vehicle()
        {
            Accessories = new List<string>();
        }

        public void ShowInfo()
        {
            Console.WriteLine($"Model: {Model}");
            Console.WriteLine($"Engine: {Engine}");
            Console.WriteLine($"Body: {Body}");
            Console.WriteLine($"Transmission: {Transmission}");
            Console.WriteLine($"Accessories:");

            foreach (var accessory in Accessories)
            {
                Console.WriteLine($"\t{accessory}");
            }
        }
    }
}
